version: "2"
services:

    gateway:
            image: docker.yhb/ywm/gateway:1.0.0
            container_name: gateway
            ports: ["9999:9999"]
            volumes: ["${DOCKER_VOLUMES}"]
            networks: ['ywm']
            restart: always
            environment:
                - APP_OPTIONS=
                    --server.port=9999  ${APP_OPTIONS}
                    --zuul.host.socket-timeout-millis=60000
                    --zuul.host.connect-timeout-millis=60000
                    --zuul.retryable=true

    user:
            image: docker.yhb/ywm/user:1.0.0
            container_name: user
            networks: ['ywm']
            volumes: ["${DOCKER_VOLUMES}"]
            restart: always
            environment:
                - JAVA_OPTIONS=-Xmx1024m -Xms512m
                - APP_OPTIONS=${APP_OPTIONS}

    blog:
            image: docker.yhb/ywm/blog:1.0.0
            container_name: blog
            networks: ['ywm']
            volumes: ["${DOCKER_VOLUMES}"]
            restart: always
            environment:
                - JAVA_OPTIONS=-Xmx1024m -Xms512m
                - APP_OPTIONS=${APP_OPTIONS}

    oms:
            image: docker.yhb/ywm/ywm-oms:1.0.0
            container_name: ywm-oms
            volumes: ["${DOCKER_VOLUMES}"]
            networks: ['ywm']
            restart: always
            environment:
                - JAVA_OPTIONS=-Xmx1024m -Xms512m
                - APP_OPTIONS=${APP_OPTIONS}
            ports: ["9091:9091"]

#    portal:
#            image: docker.yhb/ywm/ywm-portal:1.0.0
#            container_name: ywm-portal
#            volumes: ["${DOCKER_VOLUMES}"]
#            networks: ['ywm']
#            restart: always
#            environment:
#                - JAVA_OPTIONS=-Xmx1024m -Xms512m
#                - APP_OPTIONS=${APP_OPTIONS}
#            ports: ["9090:9090"]



networks:
    ywm:
        driver: ${DOCKER_DRIVER}
